# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

spring:
  application:
    name: server

server:
  port: 8090
  servlet:
    contextPath: /greetingserver